spring.application.name=plainpostingprogram
application.version=1.0-SNAPSHOT
server.port=${PORT:8888}
spring.data.mongodb.uri=mongodb://localhost:27017/plain_posting_program
logging.level.org.mongodb.driver=warn
logging.level.org.springframework.data.mongodb=warn
logging.level.org.springframework.data.mongodb.core.MongoTemplate=warn